version: "3.8"
services:
  api:
    build:
      context: ./API
      dockerfile: API/Dockerfile
    ports:
      - "5165:5165"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5165
    volumes:
      - ./API:/app
