version: '3.8'

services:
  taskmicroservice:
    build:
      context: ./OverblikPlusBackend/TaskMicroService
      dockerfile: Dockerfile
    ports:
      - "5101:80"
    env_file:
      - .env
    volumes:
      - data-protection-keys:/root/.aspnet/DataProtection-Keys

  usermicroservice:
    build:
      context: ./OverblikPlusBackend/UserMicroService
      dockerfile: Dockerfile
    ports:
      - "5102:80"
    env_file:
      - .env
    volumes:
      - data-protection-keys:/root/.aspnet/DataProtection-Keys

volumes:
  data-protection-keys:
