services:
  taskmicroservice:
    build:
      context: ./OverblikPlusBackend
      dockerfile: TaskMicroService/Dockerfile
    ports:
      - "5101:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DBConnectionString=Server=sqlserver,1433;Database=Overblikplus_Dev;User Id=sa;Password=reallyStrongPwd123;Persist Security Info=False;MultipleActiveResultSets=False;Encrypt=False;TrustServerCertificate=True;Connection Timeout=30;
      - ConnectionStrings__BlobStorageConnectionString=UseDevelopmentStorage=true;DevelopmentStorageProxyUri=http://azurite;
    depends_on:
      - azurite
      - sqlserver

  usermicroservice:
    build:
      context: ./OverblikPlusBackend
      dockerfile: UserMicroService/Dockerfile
    ports:
      - "5102:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DBConnectionString=Server=sqlserver,1433;Database=Overblikplus_Dev;User Id=sa;Password=reallyStrongPwd123;Persist Security Info=False;MultipleActiveResultSets=False;Encrypt=False;TrustServerCertificate=True;Connection Timeout=30;
      - ConnectionStrings__BlobStorageConnectionString=UseDevelopmentStorage=true;DevelopmentStorageProxyUri=http://azurite;
      - EF_CORE_MIGRATIONS=true
    depends_on:
      - azurite
      - sqlserver

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"

  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    platform: linux/arm64
    environment:
      SA_PASSWORD: "reallyStrongPwd123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
