services:
  taskmicroservice:
    image: overblikplusregistry.azurecr.io/4semester-taskmicroservice:latest
    ports:
      - "5101:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: ${DB_CONNECTION_STRING}
      BlobStorage__ConnectionString: ${BLOB_STORAGE_CONNECTION_STRING}
      ApplicationInsights__ConnectionString: ${APPLICATIONINSIGHTS_CONNECTION_STRING}
      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}

  usermicroservice:
    image: overblikplusregistry.azurecr.io/4semester-usermicroservice:latest
    ports:
      - "5102:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: ${DB_CONNECTION_STRING}
      BlobStorage__ConnectionString: ${BLOB_STORAGE_CONNECTION_STRING}
      ApplicationInsights__ConnectionString: ${APPLICATIONINSIGHTS_CONNECTION_STRING}
      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
