version: '3.8'

services:
  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - "5165:5165"
    networks:
      - mynetwork

  frontend:
    build:
      context: ./OverblikPlus
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - mynetwork

networks:
  mynetwork:
