
version: '3.8'

services:
  taskmicroservice:
    build:
      context: .
      dockerfile: OverblikPlusBackend/TaskMicroService/Dockerfile
    ports:
      - "5101:80" # Extern port : Intern container port
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=hildur.ucn.dk;Database=DMA-CSD-V23_10481979;User Id=DMA-CSD-V23_10481979;Password=Password1!;Encrypt=False;

  usermicroservice:
    build:
      context: .
      dockerfile: OverblikPlusBackend/UserMicroService/Dockerfile
    ports:
      - "5102:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=hildur.ucn.dk;Database=DMA-CSD-V23_10481979;User Id=DMA-CSD-V23_10481979;Password=Password1!;Encrypt=False;


