name: PROD - Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_frontend:
    runs-on: ubuntu-latest
    name: Build and Deploy Frontend
    steps:
      - uses: actions/checkout@v3

      # (A) Overskriv placeholders i OverblikPlus/wwwroot/appsettings.json
      - name: Replace config placeholders (Prod)
        run: |
          sed -i 's/"dev-or-prod"/"prod"/g' ./OverblikPlus/wwwroot/appsettings.json
          sed -i 's#https://placeholder-task-api.example.com#${{ secrets.TASK_API_BASE_URL_PROD }}#g' ./OverblikPlus/wwwroot/appsettings.json
          sed -i 's#https://placeholder-user-api.example.com#${{ secrets.USER_API_BASE_URL_PROD }}#g' ./OverblikPlus/wwwroot/appsettings.json
      # (B) Build + Deploy
      - name: Build And Deploy (Prod)
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # Indsæt den secret, du bruger til prod-miljø
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_MEADOW_0E5AD7903 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"

          # Path til selve dit Blazor-projekt
          app_location: "./OverblikPlus"
          # Hvis du ikke har en API-projektmappe, sæt den til ""
          api_location: ""
          # Byg i "wwwroot"
          output_location: "wwwroot"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_MEADOW_0E5AD7903 }}
          action: "close"
