name: Backend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: 8.0.x

      # Restore dependencies for all csproj files
      - name: Restore dependencies
        run: |
          for csproj in $(find . -name '*.csproj'); do
            dotnet restore "$csproj"
          done

      # Build all csproj files
      - name: Build projects
        run: |
          for csproj in $(find . -name '*.csproj'); do
            dotnet build "$csproj" --configuration Release --no-restore
          done

      # Run tests on all test projects
      - name: Run tests
        run: |
          for csproj in $(find . -name '*.Tests.csproj'); do
            dotnet test "$csproj" --no-restore --verbosity normal
          done

      # Publish all projects (adjust output path as needed)
      - name: Publish projects
        run: |
          for csproj in $(find . -name '*.csproj'); do
            dotnet publish "$csproj" --configuration Release --output ./out/$(basename "$csproj" .csproj)
          done

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy to Azure Web App
      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_MEADOW_0E5AD7903 }}
          app_location: "OverblikPlus/wwwroot"   
                       

           
