name: Backend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: 8.0.x


      - name: Restore dependencies
        run: dotnet restore "/Users/niklasduenim/Documents/Programmering/Gitten/4semester/OverblikPlusBackend/OverblikPlusBackend.sln"

      - name: Build project
        run: dotnet build "/Users/niklasduenim/Documents/Programmering/Gitten/4semester/OverblikPlusBackend/OverblikPlusBackend.sln" --configuration Release --no-restore

      - name: Run tests
        run: dotnet test "/Users/niklasduenim/Documents/Programmering/Gitten/4semester/OverblikPlusBackend/OverblikPlusBackend.sln" --no-restore --verbosity normal


      - name: Publish project
        run: dotnet publish "OverblikPlusBackend.sln" --configuration Release --output ./out

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: <OverblikPlus>       # Replace with your Azure Web App name
          slot-name: "production"                   
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./out
