name: Backend CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4.0.1
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore "OverblikPlusBackend.sln"

    - name: Build project
      run: dotnet build "OverblikPlusBackend.sln" --configuration Release --no-restore

    - name: Run tests
      run: dotnet test "OverblikPlusBackend.sln" --no-restore --verbosity normal
