name: Backend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: 8.0.x

      # Restore dependencies for all csproj files
      - name: Restore dependencies
        run: |
          for csproj in $(find . -name '*.csproj'); do
            dotnet restore "$csproj"
          done

      # Build all csproj files
      - name: Build projects
        run: |
          for csproj in $(find . -name '*.csproj'); do
            dotnet build "$csproj" --configuration Release --no-restore
          done

      # Run tests on all test projects
      - name: Run tests
        run: |
          for csproj in $(find . -name '*.Tests.csproj'); do
            dotnet test "$csproj" --no-restore --verbosity normal
          done

      # Publish all projects (adjust output path as needed)
      - name: Publish projects
        run: |
          for csproj in $(find . -name '*.csproj'); do
            dotnet publish "$csproj" --configuration Release --output ./out/$(basename "$csproj" .csproj)
          done

      # Deploy to Azure Web App (ensure publish profile is correctly configured)
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: <OverblikPlus>       # Replace with your Azure Web App name
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./out
