name: DEV - Backend CI/CD

on:
  push:
    branches:
      - Development
  pull_request:
    branches:
      - Development

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [task-api, user-api]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: 8.0.x

      - name: Install dependencies
        run: |
          dotnet restore OverblikPlusBackend/${{ matrix.service }}

      - name: Build and run tests
        run: |
          dotnet build OverblikPlusBackend/${{ matrix.service }} -c Release
          dotnet test OverblikPlusBackend/${{ matrix.service }}.Tests --no-build --verbosity normal

      - name: Login to Azure Container Registry
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_REGISTRY }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          docker build --platform linux/amd64 -t ${{ secrets.ACR_REGISTRY }}/overblikplus-${{ matrix.service }}:latest \
          -f OverblikPlusBackend/${{ matrix.service }}/Dockerfile .

      - name: Push Docker image to ACR
        run: |
          docker push ${{ secrets.ACR_REGISTRY }}/overblikplus-${{ matrix.service }}:latest

      - name: Deploy to Azure App Service
        run: |
          az webapp config container set --name overblikplus-${{ matrix.service }}-dev --resource-group OverblikPlus-ResourceGroup \
          --container-image-name ${{ secrets.ACR_REGISTRY }}/overblikplus-${{ matrix.service }}:latest \
          --container-registry-url https://${{ secrets.ACR_REGISTRY }}

      - name: Restart Azure App Service
        run: |
          az webapp restart --name overblikplus-${{ matrix.service }}-dev --resource-group OverblikPlus-ResourceGroup

      - name: Check Logs
        run: |
          az webapp log tail --name overblikplus-${{ matrix.service }}-dev --resource-group OverblikPlus-ResourceGroup
