name: DEV - CI/CD Backend

on:
  push:
    branches:
      - Development
  pull_request:
    branches:
      - Development

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [TaskMicroService, UserMicroService]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: 8.0.x

      # Restore dependencies
      - name: Restore dependencies
        run: |
          if [ "${{ matrix.service }}" == "TaskMicroService" ]; then
            dotnet restore OverblikPlusBackend/TaskMicroService/TaskMicroService.csproj
          else
            dotnet restore OverblikPlusBackend/UserMicroService/UserMicroService.csproj
          fi

      # Build the project
      - name: Build Project
        run: |
          if [ "${{ matrix.service }}" == "TaskMicroService" ]; then
            dotnet build OverblikPlusBackend/TaskMicroService/TaskMicroService.csproj -c Release
          else
            dotnet build OverblikPlusBackend/UserMicroService/UserMicroService.csproj -c Release
          fi

      # **Run tests with specific path check**
      - name: Test Project
        run: |
          if [ "${{ matrix.service }}" == "TaskMicroService" ]; then
            testPath="OverblikPlusBackend/TaskMicroService.Tests/bin/Debug/net8.0/TaskMicroService.Tests.dll"
          else
            testPath="OverblikPlusBackend/UserMicroService.Tests/bin/Debug/net8.0/UserMicroService.Tests.dll"
          fi

          # Kontroller, om testfilen findes
          if [ ! -f "$testPath" ]; then
            echo "Test file $testPath not found!"
            exit 1
          fi

          # Kør testene
          dotnet test $testPath --logger "trx;LogFileName=test-results.trx"

      # Upload test resultater
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.service }}
          path: OverblikPlusBackend/${{ matrix.service }}.Tests/TestResults/test-results.trx

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ACR_REGISTRY }}/overblikplus-${{ matrix.service }}:latest \
          -f OverblikPlusBackend/${{ matrix.service }}/Dockerfile .

      # Push Docker image to ACR
      - name: Push Docker image to ACR
        run: |
          docker push ${{ secrets.ACR_REGISTRY }}/overblikplus-${{ matrix.service }}:latest

      # Deploy to Azure
      - name: Update Azure App Service
        run: |
          az webapp config container set --name overblikplus-${{ matrix.service }}-dev --resource-group OverblikPlus-ResourceGroup \
          --container-image-name ${{ secrets.ACR_REGISTRY }}/overblikplus-${{ matrix.service }}:latest \
          --container-registry-url https://${{ secrets.ACR_REGISTRY }}

      - name: Restart Azure App Service
        run: |
          az webapp restart --name overblikplus-${{ matrix.service }}-dev --resource-group OverblikPlus-ResourceGroup
