name: DEV - CI/CD Backend

on:
  push:
    branches:
      - Development
  pull_request:
    branches:
      - Development

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [TaskMicroService, UserMicroService]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: 8.0.x

      # Install dependencies for det valgte service
      - name: Install dependencies
        run: |
          if [ "${{ matrix.service }}" == "TaskMicroService" ]; then
            dotnet restore OverblikPlusBackend/TaskMicroService/TaskMicroService.csproj
          else
            dotnet restore OverblikPlusBackend/UserMicroService/UserMicroService.csproj
          fi

      # Build projektet
      - name: Build Project
        run: |
          if [ "${{ matrix.service }}" == "TaskMicroService" ]; then
            dotnet build OverblikPlusBackend/TaskMicroService/TaskMicroService.csproj -c Release
          else
            dotnet build OverblikPlusBackend/UserMicroService/UserMicroService.csproj -c Release
          fi

      - name: Run tests
        run: |
          if [ "${{ matrix.service }}" == "TaskMicroService" ]; then
            dotnet test OverblikPlusBackend/TaskMicroService.Test/TaskMicroService.Test.csproj --no-build --verbosity normal
          else
            dotnet test OverblikPlusBackend/UserMicroService.Tests/UserMicroService.Tests.csproj --no-build --verbosity normal
          fi



      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ACR_REGISTRY }}/overblikplus-${{ matrix.service }}:latest \
          -f OverblikPlusBackend/${{ matrix.service }}/Dockerfile .

      # Push Docker image to ACR
      - name: Push Docker image to ACR
        run: |
          docker push ${{ secrets.ACR_REGISTRY }}/overblikplus-${{ matrix.service }}:latest

      # Deploy til Azure
      - name: Update Azure App Service
        run: |
          az webapp config container set --name overblikplus-${{ matrix.service }}-dev --resource-group OverblikPlus-ResourceGroup \
          --container-image-name ${{ secrets.ACR_REGISTRY }}/overblikplus-${{ matrix.service }}:latest \
          --container-registry-url https://${{ secrets.ACR_REGISTRY }}

      - name: Restart Azure App Service
        run: |
          az webapp restart --name overblikplus-${{ matrix.service }}-dev --resource-group OverblikPlus-ResourceGroup
