name: DEV - Backend CI/CD

on:
  push:
    branches:
      - Development
  pull_request:
    branches:
      - Development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [TaskMicroService, UserMicroService] # Opdaterede navne til services

    steps:
      # Henter koden fra repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Sætter .NET SDK op
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: 8.0.x

      # Logger ind i Azure Container Registry
      - name: Login to Azure Container Registry
        run: |
          az acr login --name overblikplusregistry

      # Bygger Docker image med korrekt sti
      - name: Build Docker image
        run: |
          docker build --platform linux/amd64 -t overblikplus-${{ matrix.service }}:latest -f OverblikPlusBackend/${{ matrix.service }}/Dockerfile OverblikPlusBackend/${{ matrix.service }}

      # Push Docker image til Azure Container Registry
      - name: Push Docker image to ACR
        run: |
          docker tag overblikplus-${{ matrix.service }}:latest overblikplusregistry.azurecr.io/overblikplus-${{ matrix.service }}:latest
          docker push overblikplusregistry.azurecr.io/overblikplus-${{ matrix.service }}:latest

      # Opdaterer Azure App Service med det nye image
      - name: Update Azure App Service
        run: |
          az webapp config container set --name overblikplus-${{ matrix.service }}-dev --resource-group OverblikPlus-ResourceGroup \
          --container-image-name overblikplusregistry.azurecr.io/overblikplus-${{ matrix.service }}:latest \
          --container-registry-url https://overblikplusregistry.azurecr.io

      # Genstarter appen
      - name: Restart Azure App Service
        run: |
          az webapp restart --name overblikplus-${{ matrix.service }}-dev --resource-group OverblikPlus-ResourceGroup
