name: DEV - CI/CD Backend

on:
  push:
    branches:
      - Development
  pull_request:
    branches:
      - Development

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [TaskMicroService, UserMicroService]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: 8.0.x

      # Install dependencies
      - name: Install dependencies
        run: |
          dotnet restore OverblikPlusBackend/${{ matrix.service }}/${{ matrix.service }}.csproj

      # Build project
      - name: Build Project
        run: |
          dotnet build OverblikPlusBackend/${{ matrix.service }}/${{ matrix.service }}.csproj -c Release --no-restore

      # Run tests
      - name: Run tests
        run: |
          dotnet test OverblikPlusBackend/${{ matrix.service }}.Test/${{ matrix.service }}.Test.csproj -c Release --no-build \
          --logger "trx;LogFileName=test-results.trx"

      # Archive test results
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Test Results (${{ matrix.service }})
          path: OverblikPlusBackend/${{ matrix.service }}.Test/TestResults/test-results.trx

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build --platform linux/amd64 -t ${{ secrets.ACR_REGISTRY }}/overblikplus-${{ matrix.service }}:latest \
          -f OverblikPlusBackend/${{ matrix.service }}/Dockerfile .

      # Push Docker image to ACR
      - name: Push Docker image to ACR
        run: |
          docker push ${{ secrets.ACR_REGISTRY }}/overblikplus-${{ matrix.service }}:latest

      # Deploy to Azure
      - name: Update Azure App Service
        run: |
          az webapp config container set --name overblikplus-${{ matrix.service }}-dev --resource-group OverblikPlus-ResourceGroup \
          --container-image-name ${{ secrets.ACR_REGISTRY }}/overblikplus-${{ matrix.service }}:latest \
          --container-registry-url https://${{ secrets.ACR_REGISTRY }}

      - name: Restart Azure App Service
        run: |
          az webapp restart --name overblikplus-${{ matrix.service }}-dev --resource-group OverblikPlus-ResourceGroup
