name: DEV - Backend CI/CD

on:
  push:
    branches:
      - Development
  pull_request:
    branches:
      - Development
  workflow_dispatch: # Allow manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Bygger og deployer både user-api og task-api
        service: [user-api, task-api]

    steps:
      # 1. Tjekker koden ud
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Sætter .NET SDK op
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # 3. Azure Login (via secrets.AZURE_CREDENTIALS)
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 4. Tjek login
      - name: Azure Login Check
        run: |
          az account show
      

     # 5. Overskriv placeholders
      - name: Replace config placeholders (Dev)
        run: |
          echo "Updating TaskMicroService configuration..."
          DB_CONN=$(echo "${{ secrets.DB_CONNECTION_STRING_DEV }}" | tr -d '\n')
          BLOB_CONN=$(echo "${{ secrets.BLOB_STORAGE_CONNECTION_STRING_DEV }}" | tr -d '\n')
          JWT_KEY=$(echo "${{ secrets.JWT_KEY_DEV }}" | tr -d '\n')
          JWT_ISSUER=$(echo "${{ secrets.JWT_ISSUER_DEV }}" | tr -d '\n')
          JWT_AUDIENCE=$(echo "${{ secrets.JWT_AUDIENCE_DEV }}" | tr -d '\n')
          BLOB_URL=$(echo "${{ secrets.BLOB_BASE_URL_DEV }}" | tr -d '\n')
          ENC_KEY=$(echo "${{ secrets.ENCRYPTION_KEY }}" | tr -d '\n')

          echo "DB_CONN length: ${#DB_CONN}"
          echo "JWT_AUDIENCE: $JWT_AUDIENCE"
          
          # Echo connection string for debugging (mask sensitive parts)
          DB_CONN_MASKED=$(echo "$DB_CONN" | sed 's/Password=[^;]*/Password=***MASKED***/g')
          echo "DB_CONNECTION_STRING (masked): $DB_CONN_MASKED"

          echo "BLOB_CONN length: ${#BLOB_CONN}"
          echo "JWT_AUDIENCE length: ${#JWT_AUDIENCE}"

          sed -i "s/\"dev-or-prod\"/\"dev\"/g" ./OverblikPlusBackend/TaskMicroService/appsettings.json
          sed -i "s#DBConnectionStringPlaceholder#$DB_CONN#g" ./OverblikPlusBackend/TaskMicroService/appsettings.json
          sed -i "s#BlobStorageConnectionStringPlaceholder#$BLOB_CONN#g" ./OverblikPlusBackend/TaskMicroService/appsettings.json
          sed -i "s#KeyPlaceholder#$JWT_KEY#g" ./OverblikPlusBackend/TaskMicroService/appsettings.json
          sed -i "s#IssuerPlaceholder#$JWT_ISSUER#g" ./OverblikPlusBackend/TaskMicroService/appsettings.json
          sed -i "s#AudiencePlaceholder#$JWT_AUDIENCE#g" ./OverblikPlusBackend/TaskMicroService/appsettings.json
          sed -i "s#BlobStorageBaseUrlPlaceholder#$BLOB_URL#g" ./OverblikPlusBackend/TaskMicroService/appsettings.json

          echo "Updating UserMicroService configuration..."
          sed -i "s#DBConnectionStringPlaceholder#$DB_CONN#g" ./OverblikPlusBackend/UserMicroService/appsettings.json
          sed -i "s#EncryptionKeyPlaceholder#$ENC_KEY#g" ./OverblikPlusBackend/UserMicroService/appsettings.json
          sed -i "s#KeyPlaceholder#$JWT_KEY#g" ./OverblikPlusBackend/UserMicroService/appsettings.json
          sed -i "s#IssuerPlaceholder#$JWT_ISSUER#g" ./OverblikPlusBackend/UserMicroService/appsettings.json
          sed -i "s#AudiencePlaceholder#$JWT_AUDIENCE#g" ./OverblikPlusBackend/UserMicroService/appsettings.json

          echo "Configuration updated successfully."
      
      # 6. Gendanner afhængigheder
      - name: Restore dependencies
        run: |
          for csproj in $(find . -name '*.csproj'); do
            dotnet restore "$csproj"
          done

      # 7. Bygger projekterne (Release)
      - name: Build projects
        run: |
          for csproj in $(find . -name '*.csproj'); do
            dotnet build "$csproj" --configuration Release --no-restore
          done

      # 8. Kører tests (ekskl. evt. frontend-tests)
      - name: Run tests
        run: |
          for csproj in $(find . -name '*.Tests.csproj' ! -name '*OverblikPlus.Frontend.Tests*'); do
            dotnet test "$csproj" --no-restore --verbosity normal
          done

      # 9. Login til Azure Container Registry (ACR)
      - name: Login to Azure Container Registry
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_REGISTRY }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      # 10. Bygger Docker-billedet
      - name: Build Docker image
        run: |
          docker build --platform linux/amd64 \
            -t ${{ secrets.ACR_REGISTRY }}/overblikplus-${{ matrix.service }}-dev:latest \
            -f OverblikPlusBackend/${{ matrix.service == 'user-api' && 'UserMicroService/Dockerfile' || 'TaskMicroService/Dockerfile' }} \
            --build-arg SHARED_PROJECT_PATH=OverblikPlusBackend/OverblikPlus.Shared \
            OverblikPlusBackend

      # 11. Pusher Docker-billedet til ACR
      - name: Push Docker image to ACR
        run: |
          docker push ${{ secrets.ACR_REGISTRY }}/overblikplus-${{ matrix.service }}-dev:latest

      # 12. Opdater Azure App Service til det nyeste Docker-image
      - name: Update Azure App Service
        run: |
          az webapp config container set \
            --name overblikplus-${{ matrix.service }}-dev \
            --resource-group OverblikPlus-ResourceGroup \
            --container-image-name ${{ secrets.ACR_REGISTRY }}/overblikplus-${{ matrix.service }}-dev:latest \
            --container-registry-url https://${{ secrets.ACR_REGISTRY }}

      # 13. Genstart Azure App Service så ny config slår igennem
      - name: Restart Azure App Service
        run: |
          az webapp restart \
            --name overblikplus-${{ matrix.service }}-dev \
            --resource-group OverblikPlus-ResourceGroup
