name: PROD - Backend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Bygger og deployer både user-api og task-api
        service: [user-api, task-api]

    steps:
      # 1. Tjekker koden ud
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Sætter .NET SDK op
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # 3. Azure Login (via secrets.AZURE_CREDENTIALS)
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 4. (Valgfri) Tjek login
      - name: Azure Login Check
        run: |
          az account show
          
      # 12. Overskriv placeholders
      - name: Replace config placeholders (Prod)
        run: |
          sed -i 's/"dev-or-prod"/"prod"/g' ./OverblikPlusBackend/TaskMicroService/appsettings.json
          sed -i 's#DBConnectionStringPlaceholder#${{ secrets.DB_CONNECTION_STRING_PROD }}#g' ./OverblikPlusBackend/TaskMicroService/appsettings.json
          sed -i 's#BlobStorageConnectionString#${{ secrets.BLOB_STORAGE_CONNECTION_STRING_PROD }}#g' ./OverblikPlusBackend/TaskMicroService/appsettings.json
          sed -i 's#KeyPlaceholder#${{ secrets.JWT_KEY_PROD }}#g' ./OverblikPlusBackend/TaskMicroService/appsettings.json
          sed -i 's#IssuerPlaceholder#${{ secrets.JWT_ISSUER_PROD }}#g' ./OverblikPlusBackend/TaskMicroService/appsettings.json
          sed -i 's#AudiencePlaceholder#${{ secrets.JWT_AUDIENCE_PROD }}#g' ./OverblikPlusBackend/TaskMicroService/appsettings.json
          sed -i 's#BlobStorageBaseUrlPlaceholder#${{ secrets.BLOB_BASE_URL_PROD }}#g' ./OverblikPlusBackend/TaskMicroService/appsettings.json

          sed -i 's#DBConnectionStringPlaceholder#${{ secrets.DB_CONNECTION_STRING_PROD }}#g' ./OverblikPlusBackend/UserMicroService/appsettings.json
          sed -i 's#EncryptionKeyPlaceholder#${{ secrets.ENCRYPTION_KEY }}#g' ./OverblikPlusBackend/UserMicroService/appsettings.json
          sed -i 's#KeyPlaceholder#${{ secrets.JWT_KEY_PROD }}#g' ./OverblikPlusBackend/UserMicroService/appsettings.json
          sed -i 's#IssuerPlaceholder#${{ secrets.JWT_ISSUER_PROD }}#g' ./OverblikPlusBackend/UserMicroService/appsettings.json
          sed -i 's#AudiencePlaceholder#${{ secrets.BLOB_BASE_URL_PROD }}#g' ./OverblikPlusBackend/UserMicroService/appsettings.json

      # 5. Gendanner afhængigheder
      - name: Restore dependencies
        run: |
          for csproj in $(find . -name '*.csproj'); do
            dotnet restore "$csproj"
          done

      # 6. Bygger projekterne (Release)
      - name: Build projects
        run: |
          for csproj in $(find . -name '*.csproj'); do
            dotnet build "$csproj" --configuration Release --no-restore
          done

      # 7. Kører tests
      - name: Run tests
        run: |
          for csproj in $(find . -name '*.Tests.csproj' ! -name '*OverblikPlus.Frontend.Tests*'); do
            dotnet test "$csproj" --no-restore --verbosity normal
          done

      # 8. Login til Azure Container Registry (ACR)
      - name: Login to Azure Container Registry
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_REGISTRY }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      # 9. Bygger Docker-billedet
      - name: Build Docker image
        run: |
          docker build --platform linux/amd64 \
            -t ${{ secrets.ACR_REGISTRY }}/overblikplus-${{ matrix.service }}:latest \
            -f OverblikPlusBackend/${{ matrix.service == 'user-api' && 'UserMicroService/Dockerfile' || 'TaskMicroService/Dockerfile' }} \
            --build-arg SHARED_PROJECT_PATH=OverblikPlusBackend/OverblikPlus.Shared \
            OverblikPlusBackend

      # 10. Pusher Docker-billedet til ACR
      - name: Push Docker image to ACR
        run: |
          docker push ${{ secrets.ACR_REGISTRY }}/overblikplus-${{ matrix.service }}:latest

      # 11. Opdater Azure App Service til det nyeste Docker-image
      - name: Update Azure App Service
        run: |
          az webapp config container set \
            --name overblikplus-${{ matrix.service }} \
            --resource-group OverblikPlus-ResourceGroup \
            --container-image-name ${{ secrets.ACR_REGISTRY }}/overblikplus-${{ matrix.service }}:latest \
            --container-registry-url https://${{ secrets.ACR_REGISTRY }}

      # 13. Genstart Azure App Service så ny config slår igennem
      - name: Restart Azure App Service
        run: |
          az webapp restart \
            --name overblikplus-${{ matrix.service }} \
            --resource-group OverblikPlus-ResourceGroup
