name: Deploy Infrastructure with Pulumi

on:
  # Disabled - using manual Azure resource creation instead
  # push:
  #   branches: [ main ]
  #   paths: [ 'Pulumi/**' ]
  # pull_request:
  #   branches: [ main ]
  #   paths: [ 'Pulumi/**' ]
  workflow_dispatch: # Allow manual trigger

env:
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Setup Pulumi
        uses: pulumi/actions@v4
        with:
          command: install
          
      - name: Install dependencies
        run: |
          cd Pulumi
          dotnet restore
          
      - name: Preview Pulumi changes
        run: |
          cd Pulumi
          pulumi preview --stack dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Setup Pulumi
        uses: pulumi/actions@v4
        with:
          command: install
          
      - name: Install dependencies
        run: |
          cd Pulumi
          dotnet restore
          
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Deploy Infrastructure
        run: |
          cd Pulumi
          pulumi up --yes --stack dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
          
      - name: Output Infrastructure URLs
        run: |
          cd Pulumi
          echo "Static Web App URL: $(pulumi stack output staticWebAppUrl --stack dev)"
          echo "SQL Server: $(pulumi stack output sqlServerFqdn --stack dev)"
          echo "Storage Account: $(pulumi stack output storageAccountName --stack dev)"
